site_name: Kabason Docs

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    #- navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

extra:
  homepage: https://wiki.kabason.net
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/christian-kaba-b8247a157


plugins:
  - search
  - tags:
      - tag_file: tags.md
  - offline

copyright: Copyright &copy; 2024 - 2028 Christian Kaba

nav:  
  - Home Lab:
      - Introduction: index.md
      - Docker: home-lab/docker.md
      - Virtualization:
          - Proxmox VE: 
              - Overview: home-lab/virtualization/proxmox/proxmox.md
              - Proxmox VE Installation: home-lab/virtualization/proxmox/proxmox-installation.md
              - Proxmox VE Configuration: home-lab/virtualization/proxmox/proxmox-configuration.md
              - Proxmox Datacenter Manager: home-lab/virtualization/proxmox/pdmanager.md
              - Proxmox Virtual Machines: home-lab/virtualization/proxmox/vms.md
              - Proxmox Containers: home-lab/virtualization/proxmox/containers.md
          - VMWare ESXi: home-lab/virtualization/vmware/vmware.md
      - Application:
              - Audiobookshelf: home-lab/application/audiobookshelf.md
              - Authentik: home-lab/application/authentik.md
              - Bookstack: home-lab/application/bookstack.md
              - Nextcloud: home-lab/application/nextcloud.md
              - OpenVPN: home-lab/application/openvpn.md
              - Pairdrop: home-lab/application/pairdrop.md
              - Paperless-NGX: home-lab/application/paperless.md
              - Snipe-IT: home-lab/application/snipeit.md
              - Zabbix: home-lab/application/zabbix.md
      - Services:
              - Cloudflare: 
                  - Introduction: home-lab/services/cloudflare.md
                  - Cloudflare Tunnel: home-lab/services/cloudflare/cloudflaretunnel.md
            # - DNS: home-lab/services/dns.md
              - Email: home-lab/services/email.md
              - Home Assistant: home-lab/services/home-assistant.md
  
  - About: about.md
  - tags: tags.md
