site_name: Kabason Docs
site_url: https://kabason.net/
site_author: Christian Kaba
site_description: >-
  Kabason Docs is a personal knowledge base and documentation site for my home lab, projects, and interests. 
  It serves as a resource for myself and others to learn about various technologies and applications I use.

# Configuration
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  #logo: assets/logo.png
  #favicon: images/favicon.png
  
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.footnote.tooltips
    
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


# Plugins
plugins:
  - search
  - tags
  - offline

copyright: Copyright &copy; 2024 - 2028 Christian Kaba

# Additional configuration
extra:
  homepage: https://kabason.net
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/christian-kaba-b8247a157
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Page tree
nav:
  - Home: index.md
  - Containers & Virtualization:
       - index.md: home-lab/virtualization/index.md
       - Docker: home-lab/docker.md
       - Virtualization:
            - Proxmox VE: 
                  - Overview: home-lab/virtualization/proxmox/proxmox.md
                  - Proxmox VE Installation: home-lab/virtualization/proxmox/proxmox-installation.md
                  - Proxmox VE Post-Installation: home-lab/virtualization/proxmox/proxmox-configuration.md                  
                  - Proxmox Virtual Machines: home-lab/virtualization/proxmox/vms.md
                  - Proxmox Containers: home-lab/virtualization/proxmox/containers.md
                  - Proxmox Datacenter Manager: home-lab/virtualization/proxmox/pdmanager.md
            - VMWare ESXi: home-lab/virtualization/vmware/vmware.md

  - Self-Hosted Applications:
        - index.md: home-lab/application/index.md
        - Audiobookshelf: home-lab/application/audiobookshelf.md
        - Authentik: home-lab/application/authentik.md
        - Bookstack: home-lab/application/bookstack.md
        - Nextcloud: home-lab/application/nextcloud.md
        - Pairdrop: home-lab/application/pairdrop.md
        - Paperless-NGX: home-lab/application/paperless.md
        - Snipe-IT: home-lab/application/snipeit.md
        - Zabbix: home-lab/application/zabbix.md

  - Core Services & Integrations:
        - index.md: home-lab/services/index.md
        - Cloudflare: home-lab/services/cloudflare.md
      # - DNS: home-lab/services/dns.md
        - Email: home-lab/services/email.md
        - Home Assistant: home-lab/services/homeassistant.md
        - OpenVPN: home-lab/services/openvpn.md
  
  - About: about.md
  - Tags: tags.md
