#!/usr/bin/env python3
"""
Download the site's webfonts from Google Fonts and self-host them.

The site sets ``theme.font: false`` so Material never calls out to Google at
page load. This script fetches the woff2 files once, drops them in
``docs/assets/fonts/``, and writes ``docs/stylesheets/fonts.css`` with the
matching ``@font-face`` rules pointed at the local copies.

Only the latin and latin-ext subsets are kept; the docs have no Cyrillic,
Greek or Vietnamese content, and shipping those roughly triples the payload.

Re-run it to pick up upstream font revisions:

    python tools/fetch_fonts.py
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "docs" / "assets" / "fonts"
CSS_OUT = ROOT / "docs" / "stylesheets" / "fonts.css"

# a browser UA is required or Google serves the legacy truetype stylesheet
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

FAMILIES = [
    # (slug, Google font query)
    ("archivo", "Archivo:wdth,wght@62..125,400..900"),
    ("ibm-plex-sans", "IBM+Plex+Sans:wght@400;500;600"),
    ("ibm-plex-sans-italic", "IBM+Plex+Sans:ital,wght@1,400"),
    ("ibm-plex-mono", "IBM+Plex+Mono:wght@400;500;600"),
]

KEEP_SUBSETS = {"latin", "latin-ext"}

BLOCK = re.compile(
    r"/\*\s*([a-z0-9\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", re.S | re.I
)
URL = re.compile(r"url\((https://[^)]+\.woff2)\)")
PROP = re.compile(r"([a-z\-]+)\s*:\s*([^;]+);")


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    out = [
        "/* Generated by tools/fetch_fonts.py — do not edit by hand.",
        " * Archivo and IBM Plex are licensed under the SIL Open Font License 1.1;",
        " * see docs/assets/fonts/OFL.txt.",
        " */",
        "",
    ]
    downloaded = 0

    for slug, query in FAMILIES:
        css = get(
            f"https://fonts.googleapis.com/css2?family={query}&display=swap"
        ).decode("utf-8")

        kept = 0
        for subset, block in BLOCK.findall(css):
            if subset not in KEEP_SUBSETS:
                continue
            m = URL.search(block)
            if not m:
                continue

            props = dict(PROP.findall(block))
            weight = props.get("font-weight", "400").strip().replace(" ", "-")
            style = props.get("font-style", "normal").strip()
            name = f"{slug}-{style}-{weight}-{subset}.woff2"

            target = FONT_DIR / name
            if not target.exists():
                target.write_bytes(get(m.group(1)))
                downloaded += 1
            kept += 1

            local = block.replace(
                m.group(0), f"url('../assets/fonts/{name}') format('woff2')"
            )
            # the upstream block already carries format(); drop the duplicate
            local = re.sub(
                r"format\('woff2'\)\s*format\('woff2'\)",
                "format('woff2')",
                local,
            )
            out.append(f"/* {slug} — {subset} */")
            out.append(local.strip())
            out.append("")

        print(f"{slug}: kept {kept} face(s)")

    CSS_OUT.write_text("\n".join(out), encoding="utf-8")
    total = len(list(FONT_DIR.glob("*.woff2")))
    size = sum(f.stat().st_size for f in FONT_DIR.glob("*.woff2")) / 1024
    print(f"\ndownloaded {downloaded} new file(s); {total} woff2 totalling {size:.0f} KB")
    print(f"wrote {CSS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
